/**
 * /pr Skill - 生成 PR 描述
 *
 * 用法：
 * - /pr              基于 main 分支生成 PR 描述
 * - /pr --base dev   基于指定分支生成
 */

import type { SkillDefinition } from "../types"
import type { WorkflowContext } from "../../subtask"

export const prSkill: SkillDefinition = {
  name: "pr",
  description: "Generate PR description based on commits",
  aliases: ["pull-request"],
  parameters: [
    {
      name: "base",
      description: "Base branch to compare against",
      required: false,
      default: "main",
    },
  ],
  workflow: {
    name: "pr",
    description: "Generate PR description",
    steps: [
      // 1. 获取当前分支
      {
        name: "get-branch",
        type: "tool",
        tool: {
          name: "bash",
          params: { command: "git branch --show-current" },
        },
      },
      // 2. 获取 commits
      {
        name: "get-commits",
        type: "tool",
        tool: {
          name: "bash",
          params: (ctx: WorkflowContext) => {
            const base = ctx.params.base || "main"
            return { command: `git log ${base}..HEAD --oneline` }
          },
        },
      },
      // 3. 检查是否有 commits
      {
        name: "check-commits",
        type: "condition",
        condition: {
          check: (ctx: WorkflowContext) => {
            const commits = ctx.results["get-commits"]
            return typeof commits === "string" && commits.trim() !== ""
          },
          then: "get-diff-stat",
          else: "no-commits",
        },
      },
      // 4. 获取 diff 统计
      {
        name: "get-diff-stat",
        type: "tool",
        tool: {
          name: "bash",
          params: (ctx: WorkflowContext) => {
            const base = ctx.params.base || "main"
            return { command: `git diff ${base}..HEAD --stat` }
          },
        },
      },
      // 5. 获取详细 diff（限制大小）
      {
        name: "get-diff",
        type: "tool",
        tool: {
          name: "bash",
          params: (ctx: WorkflowContext) => {
            const base = ctx.params.base || "main"
            // 限制 diff 大小，避免 token 过多
            return { command: `git diff ${base}..HEAD | head -500` }
          },
        },
      },
      // 6. 生成 PR 描述
      {
        name: "generate-pr",
        type: "llm",
        llm: {
          systemPrompt: "You are a helpful assistant that generates clear and informative PR descriptions.",
          prompt: (ctx: WorkflowContext) => `Generate a PR description for the following changes.

Branch: ${ctx.results["get-branch"]}
Base: ${ctx.params.base || "main"}

Commits:
${ctx.results["get-commits"]}

File changes:
${ctx.results["get-diff-stat"]}

Diff (partial):
${ctx.results["get-diff"]}

Use this format:

## Summary
[Brief description of what this PR does - 1-2 sentences]

## Changes
- [Change 1]
- [Change 2]
- [Change 3]

## Testing
[How to test these changes]

## Notes
[Any additional notes, breaking changes, or migration steps if applicable]

Write in a clear, professional tone. Be specific about what changed.`,
          outputFormat: "text",
        },
      },
      // 7. 输出结果
      {
        name: "output",
        type: "llm",
        llm: {
          prompt: (ctx: WorkflowContext) => {
            const branch = String(ctx.results["get-branch"]).trim()
            const base = ctx.params.base || "main"
            return `# PR: ${branch} → ${base}

${ctx.results["generate-pr"]}

---
*Generated by /pr skill*`
          },
          outputFormat: "text",
        },
      },
      // 错误处理
      {
        name: "no-commits",
        type: "llm",
        llm: {
          prompt: (ctx: WorkflowContext) => {
            const base = ctx.params.base || "main"
            return `No commits found between current branch and ${base}.

Make sure you have commits that are not in ${base}, or specify a different base branch:
  /pr --base <branch>`
          },
          outputFormat: "text",
        },
      },
    ],
  },
}
