/**
 * /review Skill - 代码审查
 *
 * 用法：
 * - /review              审查 staged 变更
 * - /review --files src  审查指定文件
 * - /review --base main  审查与指定分支的差异
 */

import type { SkillDefinition } from "../types"
import type { WorkflowContext } from "../../subtask"

export const reviewSkill: SkillDefinition = {
  name: "review",
  description: "Review staged changes or specified files",
  aliases: ["cr", "code-review"],
  parameters: [
    {
      name: "files",
      description: "Files to review (default: staged changes)",
      required: false,
    },
    {
      name: "base",
      description: "Base branch to compare against",
      required: false,
    },
  ],
  workflow: {
    name: "review",
    description: "Code review workflow",
    steps: [
      // 1. 获取要审查的代码
      {
        name: "get-code",
        type: "tool",
        tool: {
          name: "bash",
          params: (ctx: WorkflowContext) => {
            if (ctx.params.files) {
              return { command: `git diff HEAD -- ${ctx.params.files}` }
            }
            if (ctx.params.base) {
              return { command: `git diff ${ctx.params.base}..HEAD` }
            }
            return { command: "git diff --staged" }
          },
        },
      },
      // 2. 检查是否有内容
      {
        name: "check-empty",
        type: "condition",
        condition: {
          check: (ctx: WorkflowContext) => {
            const code = ctx.results["get-code"]
            return typeof code === "string" && code.trim() !== ""
          },
          then: "get-file-list",
          else: "no-code",
        },
      },
      // 3. 获取变更文件列表
      {
        name: "get-file-list",
        type: "tool",
        tool: {
          name: "bash",
          params: (ctx: WorkflowContext) => {
            if (ctx.params.files) {
              return { command: `echo "${ctx.params.files}"` }
            }
            if (ctx.params.base) {
              return { command: `git diff ${ctx.params.base}..HEAD --name-only` }
            }
            return { command: "git diff --staged --name-only" }
          },
        },
      },
      // 4. 执行审查
      {
        name: "do-review",
        type: "llm",
        llm: {
          systemPrompt: `You are an experienced code reviewer. Provide constructive, actionable feedback.

Focus on:
1. Bugs and potential issues
2. Security vulnerabilities
3. Performance problems
4. Code style and readability
5. Best practices

Be specific: reference line numbers and provide examples of how to fix issues.
Be constructive: explain why something is a problem and how to improve it.
Be balanced: acknowledge good code as well as problems.`,
          prompt: (ctx: WorkflowContext) => `Please review the following code changes.

Files changed:
${ctx.results["get-file-list"]}

Diff:
\`\`\`diff
${ctx.results["get-code"]}
\`\`\`

Provide a code review with the following sections:

## Summary
[Overall assessment - is this code ready to merge?]

## Issues
[List any bugs, security issues, or problems that MUST be fixed]

## Suggestions
[List improvements that would be nice to have]

## Good Practices
[Acknowledge any particularly good code or patterns]

If there are no issues, say so clearly.`,
          outputFormat: "text",
        },
      },
      // 5. 格式化输出
      {
        name: "output",
        type: "llm",
        llm: {
          prompt: (ctx: WorkflowContext) => `# Code Review

${ctx.results["do-review"]}

---
*Generated by /review skill*`,
          outputFormat: "text",
        },
      },
      // 错误处理
      {
        name: "no-code",
        type: "llm",
        llm: {
          prompt: () => `No code to review.

Usage:
  /review              Review staged changes
  /review --files src  Review specific files
  /review --base main  Review changes compared to a branch

Stage some changes with \`git add\` first, or specify files to review.`,
          outputFormat: "text",
        },
      },
    ],
  },
}
