/**
 * /test Skill - 运行测试并分析结果
 *
 * 用法：
 * - /test              运行所有测试
 * - /test --pattern x  运行匹配的测试
 * - /test --coverage   运行测试并生成覆盖率报告
 */

import type { SkillDefinition } from "../types"
import type { WorkflowContext } from "../../subtask"

export const testSkill: SkillDefinition = {
  name: "test",
  description: "Run tests and analyze results",
  aliases: ["t"],
  parameters: [
    {
      name: "pattern",
      description: "Test file pattern or test name filter",
      required: false,
    },
    {
      name: "coverage",
      description: "Generate coverage report",
      required: false,
      default: "false",
    },
  ],
  workflow: {
    name: "test",
    description: "Run tests and analyze results",
    steps: [
      // 1. 检测测试框架
      {
        name: "detect-framework",
        type: "tool",
        tool: {
          name: "bash",
          params: {
            command: `cat package.json 2>/dev/null | grep -E '"(vitest|jest|mocha|ava|tap)"' || echo "unknown"`,
          },
        },
      },
      // 2. 检测包管理器
      {
        name: "detect-pm",
        type: "tool",
        tool: {
          name: "bash",
          params: {
            command: `if [ -f "pnpm-lock.yaml" ]; then echo "pnpm"; elif [ -f "yarn.lock" ]; then echo "yarn"; else echo "npm"; fi`,
          },
        },
      },
      // 3. 运行测试
      {
        name: "run-tests",
        type: "tool",
        tool: {
          name: "bash",
          params: (ctx: WorkflowContext) => {
            const pm = String(ctx.results["detect-pm"]).trim() || "npm"
            const framework = String(ctx.results["detect-framework"])
            const pattern = ctx.params.pattern ? ` ${ctx.params.pattern}` : ""
            const coverage = ctx.params.coverage === "true" || ctx.params.coverage === true

            // 构建测试命令
            let testCmd = "test"
            if (coverage) {
              if (framework.includes("vitest")) {
                testCmd = "test:coverage"
              } else if (framework.includes("jest")) {
                testCmd = "test -- --coverage"
              }
            }

            // pnpm/yarn/npm run test
            const runCmd = pm === "npm" ? `${pm} run` : pm
            return {
              command: `${runCmd} ${testCmd}${pattern}`,
            }
          },
        },
        optional: true, // 测试失败不中断流程
      },
      // 4. 分析结果
      {
        name: "analyze",
        type: "llm",
        llm: {
          systemPrompt: "You are a helpful assistant that analyzes test results and provides actionable insights.",
          prompt: (ctx: WorkflowContext) => `Analyze the following test output and provide a summary.

Test output:
\`\`\`
${ctx.results["run-tests"]}
\`\`\`

Provide analysis in this format:

## Test Results
[Overall status: PASSED / FAILED / ERROR]
[Number of tests passed/failed/skipped if available]

## Failed Tests
[List each failed test with:
- Test name
- Error message
- Likely cause
- Suggested fix]

## Recommendations
[Any suggestions for improving test coverage or fixing issues]

If all tests passed, congratulate and note any warnings or slow tests.
If there was an error running tests, explain what went wrong.`,
          outputFormat: "text",
        },
      },
      // 5. 输出结果
      {
        name: "output",
        type: "llm",
        llm: {
          prompt: (ctx: WorkflowContext) => `# Test Analysis

${ctx.results["analyze"]}

---
*Generated by /test skill*`,
          outputFormat: "text",
        },
      },
    ],
  },
}
